language: node_js
script: true
node_js:
 - "iojs"
 - "7"
services:
 - mysql
before_install:
  - mysql -e 'CREATE DATABASE zeus_node1;'
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql_upgrade  
  - mysql -u root -e 'CREATE DATABASE zeus_node;'
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'haritha'@'localhost' IDENTIFIED WITH mysql_native_password BY 'haritha';"
  - mysql -u root -e "GRANT ALL ON zeus_spring.* TO 'haritha'@'localhost';"


